
Parameters:

    VpcCIDR:
        Type: String
        Default: 10.0.0.0/16
        Description: This is a common VPC which will consist of every resource
    PubSubnetCIDR1:
        Type: String
        Default: 10.42.1.0/16
        Description: Public Subnet CIDR for AZ 1
    PvtSubnetCIDR1:
        Type: String
        Default: 10.42.2.0/16
        Description: Private Subnet CIDR for AZ 1
    PubSubnetCIDR2:
        Type: String
        Default: 10.42.3.0/16
        Description: Public Subnet CIDR for AZ 2
    PvtSubnetCIDR2:
        Type: String
        Default: 10.42.4.0/16
        Description: Private Subnet CIDR for AZ 2
    KeyName:
        Type: AWS::EC2::KeyPair::KeyName
        Default: new_key
    InstanceType:
        Type: String
        Default: t2.micro
  
    
Resources: 
    VPC:
        Type: 'AWS::EC2::VPC'
        Properties:
            CidrBlock: !Ref VpcCIDR
            
    PubSubnet1:
        Type: 'AWS::EC2::Subnet'
        Properties:
            CidrBlock: !Ref PubSubnetCIDR1
            VpcId: !Ref VPC
            AvailabilityZone: !Select
                              - 0
                              - Fn::GetAZs: Ref 'AWS::Region'
            MapPublicIpOnLaunch: true
    
    PvtSubnet1:
        Type: 'AWS::EC2::Subnet'
        Properties:
            CidrBlock: !Ref PvtSubnetCIDR1
            VpcId: !Ref VPC
            AvailabilityZone: !Select
                              - 0
                              - Fn::GetAZs: Ref 'AWS::Region'
            MapPublicIpOnLaunch: false

    PubSubnet2:
        Type: 'AWS::EC2::Subnet'
        Properties:
            CidrBlock: !Ref PubSubnetCIDR2
            VpcId: !Ref VPC
            AvailabilityZone: !Select
                              - 0
                              - Fn::GetAZs: Ref 'AWS::Region'
            MapPublicIpOnLaunch: true
    
    PvtSubnet2:
        Type: 'AWS::EC2::Subnet'
        Properties:
            CidrBlock: !Ref PvtSubnetCIDR2
            VpcId: !Ref VPC
            AvailabilityZone: !Select
                              - 0
                              - Fn::GetAZs: Ref 'AWS::Region'
            MapPublicIpOnLaunch: false
            
    InternetGW:
        Type: 'AWS::EC2::InternetGateway'
    
    Gateway:
        Type: 'AWS::EC2::VPCGatewayAttachment'
        Properties:
            VpcId: !Ref VPC
            InternetGatewayId: !Ref InternetGW
            
    EC2Ins1AZ1:
        Type: 'AWS::EC2::Instance'
        Properties:
            InstanceType:
                Ref: InstanceType
            KeyName:
                Ref: KeyName
            SubnetId:
                Ref: PubSubnet1
            
    EC2Ins2AZ1:
        Type: 'AWS::EC2::Instance'
        Properties:
            InstanceType:
                Ref: InstanceType
            KeyName:
                Ref: KeyName
            SubnetId:
                Ref: PvtSubnet1
            
    EC2Ins1AZ2:
        Type: 'AWS::EC2::Instance'
        Properties:
            InstanceType:
                Ref: InstanceType
            KeyName:
                Ref: KeyName
            SubnetId:
                Ref: PubSubnet2
            
    EC2Ins2AZ2:
        Type: 'AWS::EC2::Instance'
        Properties:
            InstanceType:
                Ref: InstanceType
            KeyName:
                Ref: KeyName
            SubnetId:
                Ref: PvtSubnet2
            
            
    
